name: SweetDevelopment
version: '${version}'
main: top.mrxiaom.sweet.dev.SweetDevelopment
api-version: 1.13
authors: [ MrXiaoM ]
commands:
  sweetdevelopment:
    description: 'The main command of SweetDevelopment'
    aliases: [ sdev, sd, dev ]
